sudo: false

language: go

go:
  - 1.8.3
  - tip

addons:
  apt:
    sources:
      - mongodb-3.2-precise
    packages:
      - mongodb-org-server
  artifacts:
    s3_region: us-west-2
    paths:
      - $(git ls-files -o deploy/*/*-*.tar.gz | tr "\n" ":")
    target_paths:
      - /

services:
  - mongodb

script:
  - ./build.sh
  - ./test.sh
  - ./artifact.sh

matrix:
  allow_failures:
    - go: tip

notifications:
  email:
    on_success: change
    on_failure: always
