FROM golang:1.15-alpine AS builder
ENV GO111MODULE=on
ENV XDG_CACHE_HOME="/go/src/github.com/mdblp/.cache"
WORKDIR /go/src/github.com/mdblp/
RUN apk --no-cache update && \
    apk --no-cache upgrade && \
    apk add --no-cache gcc musl-dev git rsync python3 py3-pip && \
    pip3 install openapi-spec-validator prance click && \
    adduser -D mdblp && \
    chown -R mdblp /go/src/github.com/mdblp/
USER mdblp 
COPY go.mod ./
RUN go mod download