#! /bin/bash -eu
# assumes that the build has been done at least once

export GOPATH=`pwd`

TESTDIRS=$(find . -name "*_test.go" -and ! -path "./src/*" |sed s@/[^/]*go@@ |sed s@./@@ |uniq)

for i in $TESTDIRS; do
    echo Testing in $i:
    cd $i
    go test -v
    cd ..
done
